question_translation_template = """You will be given an English question in the following format.

[Question]
<question>
{..question...}
</question>

Your job is to return a translated version of the question.
* Translate to <language>.
* The translation must be fluent, easy to read by native speakers.
* Do not solve the prompt translate it.
* You must preserve all details including math notations (latex) and code. 
* The math notations and code must not be translated, keep it as is.
* Return you translation in the following format.

[Translation]
<translation>
{..translated question...}
</translation>

--------------------------------------------------
The following is the math problem for you task:

[Question]
<question>
<source_question>
</question>"""


solution_translation_template = """You will be given an English solution in the following format.

[Solution]
<solution>
{..solution in English...}
</solution>

Your job is to rewrite the English solution to <language>. 
* The solution must preserve the original structure and details.
* You must preserve all details including math notations (latex) and code. 
* The math notations and code must not be translated, keep it as is.
* The solution must be natural, easy and polite for a native speaker to read.

[Translation]
<translation>
{..translated solution...}
</translation>

--------------------------------------------------
The following is the math problem and solution for your task:

[Solution]
<solution>
<source_solution>
</solution>"""

judge_template = r"""You will be given a math problem, the correct answer, and a solution generated by a language model. Your task is to determine whether the solution generated by the model is correct.

[Question]
<question>
{..math question...}
</question>

[Correct Answer]
<answer>
{..correct answer...}
</answer>

[Model Solution]
<solution>
{..model-generated solution...}
</solution>

Instructions:
* Compare the model’s solution with the correct answer.
* If the model’s solution is correct, output `[[TRUE]]`.
* If the model’s solution is incorrect, output `[[FALSE]]`.
* You do not have to judge the solution process; there are numerous possible 'Gold' solutions, and the model solution does not have to be identical with the one provided. As long as the model reaches the correct answer, it is correct.
* Do not provide any explanations—only return your judgment ONLY.

--------------------------------------------------
The following is the math problem and solution for your task:

[Question]
<question>
<math_question>
</question>

[Correct Answer]
<answer>
<correct_answer>
</answer>

[Model Solution]
<solution>
<model_solution>
</solution>"""

system_prompt = """You are a highly advanced language model. You must adhere strictly to the following guidelines when generating responses:

1. **Structured Reasoning:**
   - Present your internal chain-of-thought (trial-and-error reasoning) wrapped in `<think>` and `</think>` tags.
   - Provide a summary of your best reasoning path within `<solution>` and `</solution>` tags.
   - Accordingly, your output should be look like: <think>\n{trial-and-errors}\n<\think>\n<solution>\n{summary}\n<\solution>

2. **Output Format:**
   - Your complete response must be wrapped in the `\\boxed{ ... }` format.
   
3. **Language Consistency:**
   - Ensure that your final output is in the same language as the input.

Follow these instructions precisely for every response."""

language_dict = {
   'af': 'Afrikaans',
   'sq': 'Albanian',
   'ar': 'Arabic',
   'bn': 'Bengali',
   'bg': 'Bulgarian',
   'ca': 'Catalan',
   'zh-cn': 'Chinese_(Simplified)',
   'zh-tw': 'Chinese_(Traditional)',
   'hr': 'Croatian',
   'cs': 'Czech',
   'da': 'Danish',
   'nl': 'Dutch',
   'en': 'English',
   'et': 'Estonian',
   'fi': 'Finnish',
   'fr': 'French',
   'de': 'German',
   'el': 'Greek',
   'gu': 'Gujarati',
   'he': 'Hebrew',
   'hi': 'Hindi',
   'hu': 'Hungarian',
   'id': 'Indonesian',
   'it': 'Italian',
   'ja': 'Japanese',
   'kn': 'Kannada',
   'ko': 'Korean',
   'lv': 'Latvian',
   'lt': 'Lithuanian',
   'mk': 'Macedonian',
   'ml': 'Malayalam',
   'mr': 'Marathi',
   'ne': 'Nepali',
   'no': 'Norwegian',
   'fa': 'Persian',
   'pl': 'Polish',
   'pt': 'Portuguese',
   'pa': 'Punjabi',
   'ro': 'Romanian',
   'ru': 'Russian',
   'sk': 'Slovak',
   'sl': 'Slovenian',
   'so': 'Somali',
   'es': 'Spanish',
   'sw': 'Swahili',
   'sv': 'Swedish',
   'tl': 'Tagalog',
   'ta': 'Tamil',
   'te': 'Telugu',
   'th': 'Thai',
   'tr': 'Turkish',
   'uk': 'Ukrainian',
   'ur': 'Urdu',
   'vi': 'Vietnamese',
   'cy': 'Welsh'
}

dataset_name_dict = {
   "math100": "MT-MATH100",
   "aime2024": "MT-AIME2024",
   "imo": "M-IMO"
}

lang_dict = {
   14: ["Afrikaans", "Arabic", "Chinese_(Simplified)", "English", "French", "German", "Hebrew", "Indonesian", "Italian", "Japanese", "Korean", "Spanish", "Turkish", "Vietnamese"],
   41: ['Albanian', 'Bengali', 'Bulgarian', 'Catalan', 'Chinese_(Traditional)', 'Croatian', 'Czech', 'Danish', 'Dutch', 'Estonian', 'Finnish', 'Greek', 'Gujarati', 'Hindi', 'Hungarian', 'Kannada', 'Latvian', 'Lithuanian', 'Macedonian', 'Malayalam', 'Marathi', 'Nepali', 'Norwegian', 'Persian', 'Polish', 'Portuguese', 'Punjabi', 'Romanian', 'Russian', 'Slovak', 'Slovenian', 'Somali', 'Swahili', 'Swedish', 'Tagalog', 'Tamil', 'Telugu', 'Thai', 'Ukrainian', 'Urdu', 'Welsh'],
   55: ['Afrikaans', 'Albanian', 'Arabic', 'Bengali', 'Bulgarian', 'Catalan', 'Chinese_(Simplified)', 'Chinese_(Traditional)', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Estonian', 'Finnish', 'French', 'German', 'Greek', 'Gujarati', 'Hebrew', 'Hindi', 'Hungarian', 'Indonesian', 'Italian', 'Japanese', 'Kannada', 'Korean', 'Latvian', 'Lithuanian', 'Macedonian', 'Malayalam', 'Marathi', 'Nepali', 'Norwegian', 'Persian', 'Polish', 'Portuguese', 'Punjabi', 'Romanian', 'Russian', 'Slovak', 'Slovenian', 'Somali', 'Spanish', 'Swahili', 'Swedish', 'Tagalog', 'Tamil', 'Telugu', 'Thai', 'Turkish', 'Ukrainian', 'Urdu', 'Vietnamese', 'Welsh'],
   "IMO": ['Afrikaans', 'Albanian', 'Arabic', 'Bulgarian', 'Chinese_(Simplified)', 'Chinese_(Traditional)', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Estonian', 'Finnish', 'French', 'German', 'Hebrew', 'Hungarian', 'Italian', 'Japanese', 'Korean', 'Latvian', 'Lithuanian', 'Macedonian', 'Norwegian', 'Polish', 'Portuguese', 'Romanian', 'Russian', 'Slovak', 'Slovenian', 'Spanish', 'Swedish', 'Thai', 'Turkish', 'Ukrainian', 'Vietnamese', 'Indonesian', 'Greek'],
   "MMO": ['Chinese', 'Czech', 'Dutch', 'English', 'French', 'German', 'Japanese', 'Korean', 'Polish', 'Russian', 'Slovakia'],
}

system_prompt_dict = {
   "jwhj/Qwen2.5-Math-1.5B-OREO": "Please reason step by step, and put your final answer within \\boxed{}.",
   "PRIME-RL/Eurus-2-7B-PRIME": "\n\nPresent the answer in LaTex format: \\boxed{Your answer}",
   "Qwen/Qwen2.5-Math-1.5B-Instruct": "Please reason step by step, and put your final answer within \\boxed{}.",
   "Qwen/Qwen2.5-Math-7B-Instruct": "Please reason step by step, and put your final answer within \\boxed{}.",
   "Qwen/Qwen2.5-7B-Instruct": "Please reason step by step, and put your final answer within \\boxed{}.",
   "english-long-cot": "Your role as an assistant involves thoroughly exploring questions through a systematic long thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution. In the Thought section, detail your reasoning process using the specified format: <|begin_of_thought|> {thought with steps separated with '\n\n'} <|end_of_thought|> Each step should include detailed considerations such as analisying questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The solution should remain a logical, accurate, concise expression style and detail necessary step needed to reach the conclusion, formatted as follows: <|begin_of_solution|> {final formatted, precise, and clear solution} <|end_of_solution|> Now, try to solve the following question through the above guidelines:",
   "bulgarian-long-cot": "Вашата роля като асистент включва задълбочено изследване на въпросите чрез систематичен дълъг мисловен процес, преди да предоставите крайните точни и прецизни решения. Това изисква участие в цялостен цикъл на анализ, обобщение, изследване, преоценка, размишление, обратно проследяване и итерация за разработване на добре обмислен мисловен процес. Моля, структурирайте отговора си в два основни раздела: Мисъл и Решение. В раздела Мисъл детайлно опишете процеса си на разсъждение, използвайки следния формат: <|begin_of_thought|> {мисъл със стъпки, разделени с '\n\n'} <|end_of_thought|>. Всяка стъпка трябва да включва подробни съображения като анализ на въпросите, обобщаване на съответните констатации, генериране на нови идеи, проверка на точността на текущите стъпки, коригиране на грешки и преглеждане на предишни стъпки. В раздела Решение, въз основа на различни опити, изследвания и размишления от раздела Мисъл, систематично представете крайното решение, което считате за правилно. Решението трябва да остане логично, точно, кратко и да съдържа необходимите стъпки за достигане до извода, форматирано по следния начин: <|begin_of_solution|> {крайно форматирано, точно и ясно решение} <|end_of_solution|>. Сега, опитайте се да решите следния въпрос, използвайки горните насоки:",
   "chinese-long-cot": "你的角色作为助手涉及在提供最终精确准确的解决方案之前，通过系统的深度思考过程彻底探讨问题。这需要进行全面的分析、总结、探索、重新评估、反思、回溯和迭代，以形成深思熟虑的思考过程。请将你的回答结构化为两个主要部分：思考（Thought）和解决方案（Solution）。在思考部分，按照指定格式详细描述你的推理过程：<|begin_of_thought|> {思考过程，每个步骤用'\n\n'分隔} <|end_of_thought|> 每个步骤应包括详细的考量，例如分析问题、总结相关发现、头脑风暴新思路、验证当前步骤的准确性、修正错误以及回溯先前步骤。在解决方案部分，基于思考部分的各种尝试、探索和反思，系统性地呈现你认为正确的最终解决方案。解决方案应保持逻辑清晰、准确简练，并详细列出达到结论所需的必要步骤，格式如下：<|begin_of_solution|> {最终格式化、精确且清晰的解决方案} <|end_of_solution|> 现在，请按照上述指南尝试解决以下问题：",
   "swahili-long-cot": "Jukumu lako kama msaidizi linahusisha kuchunguza maswali kwa kina kupitia mchakato wa kufikiri wa muda mrefu na wa kimfumo kabla ya kutoa suluhisho la mwisho lililo sahihi na makini. Hii inahitaji kushiriki katika mzunguko kamili wa uchambuzi, muhtasari, uchunguzi, tathmini upya, tafakari, urejeleo wa hatua zilizopita, na urudufishaji ili kuendeleza mchakato wa kufikiri uliozingatiwa vyema. Tafadhali panga majibu yako katika sehemu mbili kuu: Fikra na Suluhisho. Katika sehemu ya Fikra, eleza mchakato wako wa kufikiri kwa kutumia muundo maalum: <|begin_of_thought|> {fikra zenye hatua zilizotenganishwa kwa '\n\n'} <|end_of_thought|>. Kila hatua inapaswa kujumuisha mazingatio ya kina kama vile kuchambua maswali, kutoa muhtasari wa matokeo muhimu, kubuni mawazo mapya, kuthibitisha usahihi wa hatua za sasa, kusahihisha makosa yoyote, na kurejelea hatua za awali. Katika sehemu ya Suluhisho, kwa kuzingatia majaribio mbalimbali, uchunguzi, na tafakari kutoka sehemu ya Fikra, wasilisha kwa utaratibu suluhisho la mwisho unaloliona sahihi. Suluhisho linapaswa kuwa na mtindo wa kujieleza wa kimantiki, sahihi, na mafupi huku likieleza hatua muhimu zinazohitajika kufikia hitimisho, likiwa katika muundo ufuatao: <|begin_of_solution|> {suluhisho la mwisho lililo wazi, sahihi, na lililowekwa katika muundo sahihi} <|end_of_solution|>. Sasa, jaribu kutatua swali lifuatalo kwa kutumia miongozo iliyo hapo juu:",
   "somali-long-cot": "Doorkaaga kaaliye ahaan wuxuu ku lug leeyahay in si qoto dheer loo sahamiyo su'aalaha iyada oo loo marayo hab fikir nidaamsan oo dheer kahor intaadan bixin xalal sax ah oo dhammaystiran. Tani waxay u baahan tahay in la galo wareeg dhamaystiran oo falanqeyn, soo koobid, sahaminta, dib-u-eegis, milicsi, raadraac, iyo ku celcelin si loo horumariyo hab fikir si wanaagsan loo tixgeliyay. Fadlan u qaabee jawaabtaada laba qaybood oo waaweyn: Fikir iyo Xal. Qaybta Fikirka, faahfaahi habkaaga fekerka adiga oo isticmaalaya qaabka la cayimay: <|begin_of_thought|> {fikrad oo loo kala saaray talaabooyin lagu kala soocay '\n\n'} <|end_of_thought|> Talaabo kasta waa in ay ku jiraan tixgelin faahfaahsan sida falanqeynta su’aalaha, soo koobidda natiijooyinka la xiriira, hindisidda fikrado cusub, hubinta saxnaanta talaabooyinka hadda, hagaajinta khaladaadka, iyo dib-u-eegista talaabooyinkii hore. Qaybta Xalka, iyadoo lagu saleynayo isku dayo kala duwan, sahamin, iyo milicsi laga helay qaybta Fikirka, si nidaamsan u soo bandhig xalka kama dambaysta ah ee aad u aragto inuu sax yahay. Xalka waa inuu ahaadaa mid macquul ah, sax ah, kooban, oo si faahfaahsan u tilmaamaya talaabooyinka lagama maarmaanka ah ee lagu gaarayo gabagabada, laguna habeeyay qaabkan: <|begin_of_solution|> {xalka ugu dambeeya ee habaysan, sax ah, oo cad} <|end_of_solution|> Hadda, isku day inaad xalliso su'aasha soo socota adiga oo raacaya tilmaamaha sare:",
   "english": "Please reason step by step, and put your final answer within \\boxed{}.",
   "bulgarian": "Моля, разсъждавайте стъпка по стъпка и поставете крайния си отговор в \\boxed{}.",
   "swahili-reasoning-sft": "Jukumu lako kama msaidizi linahusisha kuchunguza maswali kwa kina kupitia mchakato wa kufikiri kwa muda mrefu kabla ya kutoa masuluhisho sahihi na sahihi ya mwisho. Hii inahitaji kujihusisha katika mzunguko wa kina wa uchanganuzi, muhtasari, uchunguzi, tathmini upya, kutafakari, kurudi nyuma, na kurudia ili kukuza mchakato wa kufikiria unaozingatiwa vizuri. Tafadhali panga jibu lako katika sehemu kuu mbili: Mawazo na Suluhisho. Katika sehemu ya Mawazo, weka maelezo zaidi mchakato wako wa hoja ukitumia umbizo lililobainishwa: <|begin_of_thought|> {fikra kwa hatua zilizotenganishwa na '\n\n'} <|end_of_thought|> Kila hatua inapaswa kujumuisha mambo ya kina kama vile maswali ya uchanganuzi, muhtasari wa matokeo muhimu, kuchangia mawazo mapya, kuthibitisha usahihi wa hatua zozote za awali za hitilafu, kurekebisha hatua za awali, kurekebisha makosa. Katika sehemu ya Suluhisho, kulingana na majaribio mbalimbali, uchunguzi, na tafakari kutoka sehemu ya Mawazo, wasilisha kwa utaratibu suluhu la mwisho ambalo unaona kuwa sahihi. Suluhisho linafaa kusalia kuwa mtindo wa kujieleza wenye mantiki, sahihi, mafupi na hatua ya kina inayohitajika kufikia hitimisho, iliyoumbizwa kama ifuatavyo: <|begin_of_solution|> {suluhisho la mwisho lililoumbizwa, sahihi na la wazi} <|end_of_solution|> Sasa, jaribu kutatua swali lifuatalo kupitia miongozo iliyo hapo juu:",
   "bespokelabs/Bespoke-Stratos-7B": "Your role as an assistant involves thoroughly exploring questions through a systematic long thinking process before providing the final precise and accurate solutions. This requires engaging in a comprehensive cycle of analysis, summarizing, exploration, reassessment, reflection, backtracing, and iteration to develop well-considered thinking process. Please structure your response into two main sections: Thought and Solution. In the Thought section, detail your reasoning process using the specified format: <|begin_of_thought|> {thought with steps separated with '\n\n'} <|end_of_thought|> Each step should include detailed considerations such as analisying questions, summarizing relevant findings, brainstorming new ideas, verifying the accuracy of the current steps, refining any errors, and revisiting previous steps. In the Solution section, based on various attempts, explorations, and reflections from the Thought section, systematically present the final solution that you deem correct. The solution should remain a logical, accurate, concise expression style and detail necessary step needed to reach the conclusion, formatted as follows: <|begin_of_solution|> {final formatted, precise, and clear solution} <|end_of_solution|> Now, try to solve the following question through the above guidelines:",
   "swahili": "Tafadhali toa hoja hatua kwa hatua, na uweke jibu lako la mwisho ndani ya \\boxed{}.",
   "english-swahili": "Tafadhali sababu hatua kwa hatua kwa Kiswahili, na uweke jibu lako la mwisho ndani ya \\boxed{}.",
   "japanese": "ステップごとに順を追って説明し、最終的な答えを\\boxed{}の中に記述してください。",
   "english-japanese": "日本語で順を追って説明し、最終的な答えを \\boxed{} 内に入れてください。",
   "french": "Veuillez raisonner étape par étape, et placez votre réponse finale dans \\boxed{}.",
   "japanese-long-cot": "あなたのアシスタントとしての役割は、最終的な正確かつ精密な解答を提供する前に、体系的な長期思考プロセスを通じて質問を徹底的に探求することです。これには、分析、要約、探求、再評価、考察、バックトレース、および反復の包括的なサイクルに取り組み、十分に考慮された思考プロセスを開発する必要があります。回答は、思考と解答の2つの主要なセクションに構成してください。思考セクションでは、指定された形式を使用して推論プロセスを詳細に説明します：<|begin_of_thought|> {思考（各ステップは「\n\n」で区切られます）} <|end_of_thought|> 各ステップには、質問の分析、関連する調査結果の要約、新しいアイデアのブレインストーミング、現在のステップの正確性の検証、エラーの修正、および以前のステップの再検討などの詳細な考慮事項を含める必要があります。解答セクションでは、思考セクションからのさまざまな試み、探求、および考察に基づいて、正しいと思われる最終的な解答を体系的に提示します。解答は、論理的で正確、簡潔な表現スタイルを維持し、結論に達するために必要なステップを詳細に記述し、次のようにフォーマットします：<|begin_of_solution|> {最終的にフォーマットされた、正確で明確な解答} <|end_of_solution|> それでは、上記のガイドラインに従って、次の質問を解いてみてください。",
   "latvian": "Lūdzu, spriediet soli pa solim un ievietojiet savu galīgo atbildi \\boxed{}."
}